# shopify.theme.toml

[environments.ru9]

store = "ru9mattressvn.myshopify.com"

password = "shptka_e3256fc9559d3c49dfdd082362e9dfb9"

# (tuỳ chọn) nếu muốn pull/push vào 1 theme cụ thể:

# theme = 123456789   # ID theme (số), xem bằng "shopify theme list"

